// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Azri contributors

import { createHash } from 'node:crypto';

export interface BundleOptions {
  /** If true, inject an OG image (data-URI SVG) generated from the title. */
  generateOgImage?: boolean;
  /** Title to use for OG image generation. Falls back to <title> in the input HTML. */
  title?: string;
  /** Soft cap for warning. Default 2MB. */
  maxSizeBytes?: number;
  /** If true, minify (basic whitespace collapse). Default false (keep readable). */
  minify?: boolean;
}

export interface BundleResult {
  html: string;
  sizeBytes: number;
  contentHash: string;
  warnings: ReadonlyArray<string>;
}

const EXT_LINK_RE = /<link\b[^>]*\brel\s*=\s*["']?stylesheet["']?[^>]*>/giu;
const EXT_SCRIPT_RE = /<script\b[^>]*\bsrc\s*=\s*["']([^"']+)["'][^>]*>(\s*<\/script>)?/giu;
const TITLE_RE = /<title>([\s\S]*?)<\/title>/iu;
const HTML_ESCAPE_RE = /[<>&"]/gu;
const HEAD_CLOSE_RE = /<\/head>/iu;
const COMMENT_RE = /<!--(?!\[if).*?-->/gsu;
const TAG_GAP_RE = />\s+</gu;
const WHITESPACE_RE = /\s{2,}/gu;

function extractTitle(html: string): string {
  const m = html.match(TITLE_RE);
  return m ? m[1]!.trim() : 'Azri Explainer';
}

function makeOgSvgDataUri(title: string): string {
  const safe = title.length > 80 ? title.slice(0, 77) + '…' : title;
  const escaped = safe.replace(
    HTML_ESCAPE_RE,
    (c) =>
      ({
        '<': '&lt;',
        '>': '&gt;',
        '&': '&amp;',
        '"': '&quot;',
      })[c]!,
  );
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#fdfcf7"/><rect x="0" y="0" width="1200" height="8" fill="#2b6cb0"/><text x="60" y="320" font-family="Georgia, serif" font-size="64" fill="#1a202c" font-weight="700">${escaped}</text><text x="60" y="380" font-family="ui-monospace, monospace" font-size="20" fill="#4a5568">generated by azri</text></svg>`;
  return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);
}

function basicMinify(html: string): string {
  return html.replace(COMMENT_RE, '').replace(TAG_GAP_RE, '><').replace(WHITESPACE_RE, ' ').trim();
}

export function bundleSelfContained(html: string, opts: BundleOptions = {}): BundleResult {
  const warnings: string[] = [];
  const maxSize = opts.maxSizeBytes ?? 2 * 1024 * 1024;

  if (EXT_LINK_RE.test(html)) {
    warnings.push(
      'Found external <link rel="stylesheet"> tags; stripping for self-contained output.',
    );
    html = html.replace(EXT_LINK_RE, '');
  }

  if (EXT_SCRIPT_RE.test(html)) {
    warnings.push('Found external <script src=> tags; stripping for self-contained output.');
    html = html.replace(EXT_SCRIPT_RE, '');
  }

  if (opts.generateOgImage) {
    const title = opts.title ?? extractTitle(html);
    const ogUri = makeOgSvgDataUri(title);
    const ogMeta = `<meta property="og:image" content="${ogUri}"><meta name="twitter:image" content="${ogUri}">`;
    if (HEAD_CLOSE_RE.test(html)) {
      html = html.replace(HEAD_CLOSE_RE, `${ogMeta}</head>`);
    } else {
      warnings.push('No </head> tag found; OG image meta not injected.');
    }
  }

  if (opts.minify) {
    html = basicMinify(html);
  }

  const sizeBytes = Buffer.byteLength(html, 'utf8');
  if (sizeBytes > maxSize) {
    warnings.push(`Page size ${sizeBytes} bytes exceeds ${maxSize} bytes cap.`);
  }
  const contentHash = createHash('sha256').update(html).digest('hex');

  return { html, sizeBytes, contentHash, warnings };
}
