app = "azri"
primary_region = "iad"

[build]
dockerfile = "docs/Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_stop_machines = false
min_machines_running = 1
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "15s"
method = "GET"
path = "/healthz"
protocol = "http"
timeout = "2s"
